# Importing Dependencies

In [1]:
import numpy as np

# Matrix Basics

## Creating a Matrix using numpy

In [4]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

## Creating matrices with random values

In [9]:
matrix_3 = np.random.rand(4,4)
print(matrix_3)

[[0.20193121 0.88031406 0.91781157 0.86461952]
 [0.11988868 0.75767551 0.26862993 0.67257266]
 [0.83037217 0.52726572 0.3201431  0.79657335]
 [0.32947722 0.47618547 0.30308541 0.78423531]]


## Creating matrices with random integers

In [10]:
random_integer_matrix = np.random.randint(10,size=(4,4))
print(random_integer_matrix)

[[8 5 4 6]
 [6 3 9 7]
 [3 9 2 5]
 [3 7 8 9]]


## Matrix with all values 1

In [12]:
matrix_4 = np.ones((4,5))
print(matrix_4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# in integer
matrix_4 = np.ones((4,5), dtype=int)
print(matrix_4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Matrix with all values as 0 (Null Matrix)

In [14]:
null_matrix = np.zeros((4,5), dtype=int)
print(null_matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Creating a Identity Matrix

In [17]:
identity_matrix = np.eye(5,5,dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Transpose of a matrix

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#transposing
transpose_matrix = matrix.T
print()
print(transpose_matrix)

# #Or
# transpose_matrix = np.transpose(matrix)
# print(transpose_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Various Matrix Operations
1. Addition
2. Subtraction
3. Multiplication

## Matrix Addition

In [26]:
# creating two matrices
mat_a = np.random.randint(10,size=(3,3))
print(mat_a)

print()
mat_b = np.random.randint(10,size=(3,3))
print(mat_b)

[[5 9 2]
 [5 9 4]
 [8 4 1]]

[[6 4 4]
 [4 4 2]
 [7 7 8]]


In [27]:
mat_add = mat_a + mat_b
print(mat_add)

[[11 13  6]
 [ 9 13  6]
 [15 11  9]]


In [28]:
# alternative way
mat_add_np = np.add(mat_a, mat_b)
print(mat_add_np)

[[11 13  6]
 [ 9 13  6]
 [15 11  9]]


## Subtraction of two matrices

In [29]:
mat_sub = mat_a - mat_b
print(mat_sub)

[[-1  5 -2]
 [ 1  5  2]
 [ 1 -3 -7]]


In [30]:
# alternative way
mat_sub_np = np.subtract(mat_a, mat_b)
print(mat_sub_np)

[[-1  5 -2]
 [ 1  5  2]
 [ 1 -3 -7]]


## Multiplication of a matrix by scalar

In [36]:
x = 5
multiply_by_scalar = np.multiply(x, mat_a)
print(multiply_by_scalar)

[[25 45 10]
 [25 45 20]
 [40 20  5]]


## Multiplication of two matrices

In [32]:
print(mat_a)
print()
print(mat_b)

[[5 9 2]
 [5 9 4]
 [8 4 1]]

[[6 4 4]
 [4 4 2]
 [7 7 8]]


In [34]:
mat_multiply = np.matmul(mat_a,mat_b)
print(mat_multiply)

[[80 70 54]
 [94 84 70]
 [71 55 48]]


In [37]:
# alternatively
mat_multiply1 = np.dot(mat_a,mat_b)
print(mat_multiply1)

[[80 70 54]
 [94 84 70]
 [71 55 48]]


## Element wise multiplication

In [38]:
print(mat_a)
print()
print(mat_b)

[[5 9 2]
 [5 9 4]
 [8 4 1]]

[[6 4 4]
 [4 4 2]
 [7 7 8]]


In [39]:
mat_multiply = np.multiply(mat_a,mat_b)
print(mat_multiply)

[[30 36  8]
 [20 36  8]
 [56 28  8]]
